name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: release
        uses: madeiramadeirabr/action-generate-release@0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
